version: 0.1
phases:
  install:
    - aws cloudformation package --template-file samTemplate.yaml --s3-bucket build-pipeline-bucket --output-template-file outputsamTemplate.yaml
artifacts:
  type: zip
  files:  
    - samTemplate.yaml
    - outputsamTemplate.yaml
    